FROM node:18-alpine AS build
WORKDIR /src
ENV NODE_OPTIONS=--openssl-legacy-provider
COPY ruoyi-vue-gitee/ruoyi-ui/package*.json ./
RUN npm config set registry https://registry.npmmirror.com && npm install --no-audit --no-fund
COPY ruoyi-vue-gitee/ruoyi-ui ./
RUN npm run build:prod

FROM nginx:1.27-alpine
COPY ruoyi-vue-standalone/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /src/dist /usr/share/nginx/html
EXPOSE 80